### ISSUE TITLE
Direct your donation - zip code lookup/ state abbreviation lookup not working

### ISSUE THREAD

**Issue by rdewagan** [convio/make-a-wish-luminate-framework#23]
This is an issue on all browsers. 

When going to "direct your donation" on the first page of the donation form and selecting "local", you are unable to type in a zip code and get a local chapter. 

Steps to produce state abbreviation: 

Go to donation form 
Select Local under "Direct your donation" 
Type in  CA for California 
First result is not a California chapter. North Carolina chapters are showing when typing in California abbreviation

**Comment by noahcooper** [comment]
Fixed.

**Comment by rdewagan** [comment]
@noahcooper re-tested this one and zip code and state abbreviations seem to be working on all browsers. One issue I still see is when typing in CA. I am still getting results for North Carolina on all browsers Any specific reason for this?

**Comment by noahcooper** [comment]
Fixed.
